services:
  client:
    build: 
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./Server/.env
    depends_on:
      - server
    networks:
      - gro-network

  server:
    build: 
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    env_file:
       - ./Server/.env
    volumes:
      - ./Server:/app
      - /app/node_modules
    networks:
      - gro-network

networks:
  gro-network:
    driver: bridge
